/*
  ==============================================================================

    This file was auto-generated by the Jucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/
#include "C:/Documents and Settings/Jin/My Documents/Downloads/juce_1_52/juce/juce_amalgamated.h"

#include "../JuceLibraryCode/JuceHeader.h"
#include "MainWindow.h"


//==============================================================================
class SoundPainterApplication  : public JUCEApplication
{
public:
    //==============================================================================
    SoundPainterApplication()
    {
    }

    ~SoundPainterApplication()
    {
    }

    //==============================================================================
    void initialise (const String& commandLine)
    {
        // Do your application's initialisation code here..
        mainWindow = new MainAppWindow();
    }

    void shutdown()
    {
        // Do your application's shutdown code here..
        mainWindow = 0;
    }

    //==============================================================================
    void systemRequestedQuit()
    {

        quit();
    }

    //==============================================================================
    const String getApplicationName()
    {
        return "SoundPainter";
    }

    const String getApplicationVersion()
    {
        return ProjectInfo::versionString;
    }

    bool moreThanOneInstanceAllowed()
    {
        return true;
    }

    void anotherInstanceStarted (const String& commandLine)
    {
        
    }

private:
    ScopedPointer <MainAppWindow> mainWindow;
};

//==============================================================================
// This macro generates the main() routine that starts the app.
START_JUCE_APPLICATION(SoundPainterApplication)
/*
 * 이제 일단 사인 웨이브를 제네레이트 해서 소리를 들어보자.
 * 
*/
